### ISSUE TITLE
`test_torch_geometric.py` error while building venv in TACC environment

### ISSUE THREAD

**Issue by yjchoi1** [geoelements/gns#15]
I am trying to run it in TACC Frontera environment. While I set up a venv `sh ./build_venv.sh`, `test_torch_geometric.py` shows an error as follows:
```
test_torch_geometric.py -> no retun if import sucessful
Traceback (most recent call last):
  File "/work2/08264/baagee/frontera/gns-1/test/test_torch_geometric.py", line 2, in <module>
    import torch_geometric
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/opt/apps/intel19/python3/3.9.2/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```

**Comment by jpvantassel** [comment]
Hi @yjchoi1 
Are you running on a GPU node? Please show the full standard err and standard out.

**Comment by yjchoi1** [comment]
I was not in a GPU node, but running in GPU node still shows an error although it is a different error message

```
c197-082[rtx](831)$ sh ./build_venv.sh
Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: None

The following have been reloaded with a version change:
  1) python3/3.7.0 => python3/3.9.2

created virtual environment CPython3.9.2.final.0-64 in 5851ms
  creator CPython3Posix(dest=/work2/08264/baagee/frontera/gns-1/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home1/08264/baagee/.local/share/virtualenv)
    added seed packages: Jinja2==3.0.3, Keras_Preprocessing==1.1.2, Markdown==3.3.6, MarkupSafe==2.1.0, Pillow==9.0.1, PyYAML==6.0, Werkzeug==2.0.3, absl_py==1.0.0, astunparse==1.6.3, autopep8==1.6.0, cachetools==5.0.0, certifi==2021.10.8, charset_normalizer==2.0.12, cycler==0.11.0, dill==0.3.4, dm_tree==0.1.6, flatbuffers==2.0, fonttools==4.29.1, gast==0.5.3, google_auth==2.6.0, google_auth_oauthlib==0.4.6, google_pasta==0.2.0, googleapis_common_protos==1.55.0, googledrivedownloader==0.4, grpcio==1.44.0, idna==3.3, importlib_metadata==4.11.2, isodate==0.6.1, joblib==1.1.0, keras==2.8.0, kiwisolver==1.3.2, libclang==13.0.0, matplotlib==3.5.1, networkx==2.6.3, numpy==1.22.2, oauthlib==3.2.0, opt_einsum==3.3.0, packaging==21.3, pandas==1.4.1, pip==21.0.1, promise==2.3, protobuf==3.19.4, pyasn1==0.4.8, pyasn1_modules==0.2.8, pycodestyle==2.8.0, pyparsing==3.0.7, python_dateutil==2.8.2, pytz==2021.3, rdflib==6.1.1, requests==2.27.1, requests_oauthlib==1.3.1, rsa==4.8, scikit_learn==1.0.2, scipy==1.8.0, setuptools==60.6.0, six==1.16.0, tensorboard==2.8.0, tensorboard_data_server==0.6.1, tensorboard_plugin_wit==1.8.1, tensorflow==2.8.0, tensorflow_datasets==4.5.2, tensorflow_io_gcs_filesystem==0.24.0, tensorflow_metadata==1.7.0, termcolor==1.1.0, tf_estimator_nightly==2.8.0.dev2021122109, threadpoolctl==3.1.0, toml==0.10.2, torch==1.10.2, torch_cluster==1.5.9, torch_geometric==2.0.3, torch_scatter==2.0.9, torch_sparse==0.6.12, tqdm==4.63.0, typing_extensions==4.1.1, urllib3==1.26.8, wheel==0.37.1, wrapt==1.13.3, yacs==0.1.8, zipp==3.7.0
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
/work2/08264/baagee/frontera/gns-1/venv/bin/pip3
Looking in links: https://download.pytorch.org/whl/cu111/torch_stable.html
Collecting torch==1.10.0+cu111
  Using cached https://download.pytorch.org/whl/cu111/torch-1.10.0%2Bcu111-cp39-cp39-linux_x86_64.whl (2137.6 MB)
Collecting torchvision==0.11.1+cu111
  Using cached https://download.pytorch.org/whl/cu111/torchvision-0.11.1%2Bcu111-cp39-cp39-linux_x86_64.whl (24.5 MB)
Collecting torchaudio==0.10.0+cu111
  Using cached https://download.pytorch.org/whl/cu111/torchaudio-0.10.0%2Bcu111-cp39-cp39-linux_x86_64.whl (3.0 MB)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.9/site-packages (from torch==1.10.0+cu111) (4.1.1)
Requirement already satisfied: numpy in ./venv/lib/python3.9/site-packages (from torchvision==0.11.1+cu111) (1.22.2)
Requirement already satisfied: pillow!=8.3.0,>=5.3.0 in ./venv/lib/python3.9/site-packages (from torchvision==0.11.1+cu111) (9.0.1)
Installing collected packages: torch, torchvision, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 1.10.2
    Uninstalling torch-1.10.2:
      Successfully uninstalled torch-1.10.2
Successfully installed torch-1.10.0+cu111 torchaudio-0.10.0+cu111 torchvision-0.11.1+cu111
WARNING: You are using pip version 21.0.1; however, version 22.0.3 is available.
You should consider upgrading via the '/work2/08264/baagee/frontera/gns-1/venv/bin/python -m pip install --upgrade pip' command.
Looking in links: https://data.pyg.org/whl/torch-1.10.0+cu111.html
Requirement already satisfied: torch-spline-conv in ./venv/lib/python3.9/site-packages (1.2.1)
WARNING: You are using pip version 21.0.1; however, version 22.0.3 is available.
You should consider upgrading via the '/work2/08264/baagee/frontera/gns-1/venv/bin/python -m pip install --upgrade pip' command.
Looking in links: https://data.pyg.org/whl/torch-1.10.0+cu111.html
Requirement already satisfied: torch-scatter in ./venv/lib/python3.9/site-packages (2.0.9)
Requirement already satisfied: torch-sparse in ./venv/lib/python3.9/site-packages (0.6.12)
Requirement already satisfied: torch-cluster in ./venv/lib/python3.9/site-packages (1.5.9)
Requirement already satisfied: torch-geometric in ./venv/lib/python3.9/site-packages (2.0.3)
Requirement already satisfied: pandas in ./venv/lib/python3.9/site-packages (from torch-geometric) (1.4.1)
Requirement already satisfied: numpy in ./venv/lib/python3.9/site-packages (from torch-geometric) (1.22.2)
Requirement already satisfied: yacs in ./venv/lib/python3.9/site-packages (from torch-geometric) (0.1.8)
Requirement already satisfied: rdflib in ./venv/lib/python3.9/site-packages (from torch-geometric) (6.1.1)
Requirement already satisfied: scipy in ./venv/lib/python3.9/site-packages (from torch-geometric) (1.8.0)
Requirement already satisfied: pyparsing in ./venv/lib/python3.9/site-packages (from torch-geometric) (3.0.7)
Requirement already satisfied: scikit-learn in ./venv/lib/python3.9/site-packages (from torch-geometric) (1.0.2)
Requirement already satisfied: requests in ./venv/lib/python3.9/site-packages (from torch-geometric) (2.27.1)
Requirement already satisfied: networkx in ./venv/lib/python3.9/site-packages (from torch-geometric) (2.6.3)
Requirement already satisfied: PyYAML in ./venv/lib/python3.9/site-packages (from torch-geometric) (6.0)
Requirement already satisfied: googledrivedownloader in ./venv/lib/python3.9/site-packages (from torch-geometric) (0.4)
Requirement already satisfied: tqdm in ./venv/lib/python3.9/site-packages (from torch-geometric) (4.63.0)
Requirement already satisfied: jinja2 in ./venv/lib/python3.9/site-packages (from torch-geometric) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.9/site-packages (from jinja2->torch-geometric) (2.1.0)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.9/site-packages (from pandas->torch-geometric) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in ./venv/lib/python3.9/site-packages (from pandas->torch-geometric) (2.8.2)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas->torch-geometric) (1.16.0)
Requirement already satisfied: isodate in ./venv/lib/python3.9/site-packages (from rdflib->torch-geometric) (0.6.1)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (from rdflib->torch-geometric) (60.6.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./venv/lib/python3.9/site-packages (from requests->torch-geometric) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.9/site-packages (from requests->torch-geometric) (1.26.8)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.9/site-packages (from requests->torch-geometric) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests->torch-geometric) (2021.10.8)
Requirement already satisfied: joblib>=0.11 in ./venv/lib/python3.9/site-packages (from scikit-learn->torch-geometric) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./venv/lib/python3.9/site-packages (from scikit-learn->torch-geometric) (3.1.0)
WARNING: You are using pip version 21.0.1; however, version 22.0.3 is available.
You should consider upgrading via the '/work2/08264/baagee/frontera/gns-1/venv/bin/python -m pip install --upgrade pip' command.
Requirement already satisfied: absl-py in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: autopep8 in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.6.0)
Requirement already satisfied: tensorflow in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: tensorflow-datasets in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.5.2)
Requirement already satisfied: numpy in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (1.22.2)
Requirement already satisfied: dm-tree in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.1.6)
Requirement already satisfied: matplotlib in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (3.5.1)
Requirement already satisfied: torch in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (1.10.0+cu111)
Requirement already satisfied: torch_geometric in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (2.0.3)
Requirement already satisfied: torch_sparse in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (0.6.12)
Requirement already satisfied: torch_scatter in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (2.0.9)
Requirement already satisfied: torch-cluster in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (1.5.9)
Requirement already satisfied: six in ./venv/lib/python3.9/site-packages (from absl-py->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: pycodestyle>=2.8.0 in ./venv/lib/python3.9/site-packages (from autopep8->-r requirements.txt (line 2)) (2.8.0)
Requirement already satisfied: toml in ./venv/lib/python3.9/site-packages (from autopep8->-r requirements.txt (line 2)) (0.10.2)
Requirement already satisfied: pillow>=6.2.0 in ./venv/lib/python3.9/site-packages (from matplotlib->-r requirements.txt (line 7)) (9.0.1)
Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.9/site-packages (from matplotlib->-r requirements.txt (line 7)) (4.29.1)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.9/site-packages (from matplotlib->-r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.9/site-packages (from matplotlib->-r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.9/site-packages (from matplotlib->-r requirements.txt (line 7)) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in ./venv/lib/python3.9/site-packages (from matplotlib->-r requirements.txt (line 7)) (3.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in ./venv/lib/python3.9/site-packages (from matplotlib->-r requirements.txt (line 7)) (1.3.2)
Requirement already satisfied: keras<2.9,>=2.8.0rc0 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: google-pasta>=0.1.1 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (0.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (4.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (1.44.0)
Requirement already satisfied: h5py>=2.9.0 in /opt/apps/intel19/impi19_0/python3/3.9.2/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (3.2.1)
Requirement already satisfied: tensorboard<2.9,>=2.8 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: flatbuffers>=1.12 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (2.0)
Requirement already satisfied: gast>=0.2.1 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (0.5.3)
Requirement already satisfied: termcolor>=1.1.0 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: astunparse>=1.6.0 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (1.6.3)
Requirement already satisfied: libclang>=9.0.1 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (13.0.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (1.1.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (0.24.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (60.6.0)
Requirement already satisfied: protobuf>=3.9.2 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (3.19.4)
Requirement already satisfied: opt-einsum>=2.3.2 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (3.3.0)
Requirement already satisfied: tf-estimator-nightly==2.8.0.dev2021122109 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (2.8.0.dev2021122109)
Requirement already satisfied: wrapt>=1.11.0 in ./venv/lib/python3.9/site-packages (from tensorflow->-r requirements.txt (line 3)) (1.13.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in ./venv/lib/python3.9/site-packages (from astunparse>=1.6.0->tensorflow->-r requirements.txt (line 3)) (0.37.1)
Requirement already satisfied: mpi4py>=3.0.0 in /opt/apps/intel19/impi19_0/python3/3.9.2/lib/python3.9/site-packages (from h5py>=2.9.0->tensorflow->-r requirements.txt (line 3)) (3.0.3)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in ./venv/lib/python3.9/site-packages (from tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (0.6.1)
Requirement already satisfied: markdown>=2.6.8 in ./venv/lib/python3.9/site-packages (from tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (3.3.6)
Requirement already satisfied: requests<3,>=2.21.0 in ./venv/lib/python3.9/site-packages (from tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (2.27.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./venv/lib/python3.9/site-packages (from tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (1.8.1)
Requirement already satisfied: werkzeug>=0.11.15 in ./venv/lib/python3.9/site-packages (from tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (2.0.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in ./venv/lib/python3.9/site-packages (from tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (2.6.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./venv/lib/python3.9/site-packages (from tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: rsa<5,>=3.1.4 in ./venv/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (4.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./venv/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (5.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./venv/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./venv/lib/python3.9/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in ./venv/lib/python3.9/site-packages (from markdown>=2.6.8->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (4.11.2)
Requirement already satisfied: zipp>=0.5 in ./venv/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (3.7.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./venv/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./venv/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (3.3)
Requirement already satisfied: oauthlib>=3.0.0 in ./venv/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow->-r requirements.txt (line 3)) (3.2.0)
Requirement already satisfied: tqdm in ./venv/lib/python3.9/site-packages (from tensorflow-datasets->-r requirements.txt (line 4)) (4.63.0)
Requirement already satisfied: promise in ./venv/lib/python3.9/site-packages (from tensorflow-datasets->-r requirements.txt (line 4)) (2.3)
Requirement already satisfied: dill in ./venv/lib/python3.9/site-packages (from tensorflow-datasets->-r requirements.txt (line 4)) (0.3.4)
Requirement already satisfied: tensorflow-metadata in ./venv/lib/python3.9/site-packages (from tensorflow-datasets->-r requirements.txt (line 4)) (1.7.0)
Requirement already satisfied: scipy in ./venv/lib/python3.9/site-packages (from torch_geometric->-r requirements.txt (line 9)) (1.8.0)
Requirement already satisfied: scikit-learn in ./venv/lib/python3.9/site-packages (from torch_geometric->-r requirements.txt (line 9)) (1.0.2)
Requirement already satisfied: rdflib in ./venv/lib/python3.9/site-packages (from torch_geometric->-r requirements.txt (line 9)) (6.1.1)
Requirement already satisfied: googledrivedownloader in ./venv/lib/python3.9/site-packages (from torch_geometric->-r requirements.txt (line 9)) (0.4)
Requirement already satisfied: networkx in ./venv/lib/python3.9/site-packages (from torch_geometric->-r requirements.txt (line 9)) (2.6.3)
Requirement already satisfied: jinja2 in ./venv/lib/python3.9/site-packages (from torch_geometric->-r requirements.txt (line 9)) (3.0.3)
Requirement already satisfied: yacs in ./venv/lib/python3.9/site-packages (from torch_geometric->-r requirements.txt (line 9)) (0.1.8)
Requirement already satisfied: PyYAML in ./venv/lib/python3.9/site-packages (from torch_geometric->-r requirements.txt (line 9)) (6.0)
Requirement already satisfied: pandas in ./venv/lib/python3.9/site-packages (from torch_geometric->-r requirements.txt (line 9)) (1.4.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.9/site-packages (from jinja2->torch_geometric->-r requirements.txt (line 9)) (2.1.0)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.9/site-packages (from pandas->torch_geometric->-r requirements.txt (line 9)) (2021.3)
Requirement already satisfied: isodate in ./venv/lib/python3.9/site-packages (from rdflib->torch_geometric->-r requirements.txt (line 9)) (0.6.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./venv/lib/python3.9/site-packages (from scikit-learn->torch_geometric->-r requirements.txt (line 9)) (3.1.0)
Requirement already satisfied: joblib>=0.11 in ./venv/lib/python3.9/site-packages (from scikit-learn->torch_geometric->-r requirements.txt (line 9)) (1.1.0)
Requirement already satisfied: googleapis-common-protos<2,>=1.52.0 in ./venv/lib/python3.9/site-packages (from tensorflow-metadata->tensorflow-datasets->-r requirements.txt (line 4)) (1.55.0)
WARNING: You are using pip version 21.0.1; however, version 22.0.3 is available.
You should consider upgrading via the '/work2/08264/baagee/frontera/gns-1/venv/bin/python -m pip install --upgrade pip' command.
which python -> venv
/work2/08264/baagee/frontera/gns-1/venv/bin/python
test_pytorch.py -> random tensor
tensor([[0.4808, 0.6585, 0.1104],
        [0.4065, 0.5027, 0.6362],
        [0.1741, 0.6234, 0.4340],
        [0.8986, 0.2008, 0.5707],
        [0.8538, 0.1950, 0.9598]])
test_pytorch_cuda_gpu.py -> True if GPU
True
cuda
test_torch_geometric.py -> no retun if import sucessful
Traceback (most recent call last):
  File "/work2/08264/baagee/frontera/gns-1/test/test_torch_geometric.py", line 3, in <module>
    from torch_geometric.nn import MessagePassing, radius_graph
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .sequential import Sequential
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_geometric/nn/sequential.py", line 10, in <module>
    from torch_geometric.nn.conv.utils.jit import class_from_module_repr
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_geometric/nn/conv/__init__.py", line 24, in <module>
    from .spline_conv import SplineConv
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_geometric/nn/conv/spline_conv.py", line 16, in <module>
    from torch_spline_conv import spline_basis, spline_weighting
  File "/work2/08264/baagee/frontera/gns-1/venv/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
```
